# Generated by Django 3.2.9 on 2021-11-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('model', models.CharField(default=None, max_length=255, null=True)),
                ('speed', models.IntegerField(default=None, null=True)),
                ('average_speed', models.IntegerField(default=None, null=True)),
                ('temperature', models.FloatField(default=None, null=True)),
                ('fuel_level', models.IntegerField(default=None, null=True)),
                ('engine_status', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
