# Generated by Django 3.2.9 on 2021-11-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='name',
            new_name='make',
        ),
    ]
